version: '3.12'

services:
  app:
    build: .
    volumes:
      - .:/django
    image: app:Django_web
    container_name: Django_web  
    command: ["wait-for-it", "postgres:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:your_postgres_password@postgres:5432/your_database_name

  postgres:
    image: postgres:latest
    container_name: djangoDB
    environment:
      POSTGRES_DB: djangoDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

    ports:
      - "5432:5432"
